version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - QUEUE_CONNECTION=database
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tracktik_integration_api
      - DB_USERNAME=appuser
      - DB_PASSWORD=apppass
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=tracktik_integration_api
      - MYSQL_ROOT_PASSWORD=secret123
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=secret123

    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network:
    driver: bridge